### PR TITLE
Sql stuff 

### PR DESCRIPTION
**Pull request by cheeseonamonkey**
and package.json addition

### CODE REVIEW

**Comment by hdbham** [comment]
I don't think buffer to string is the appropriate approach. Better for the asynchronous connection if not held in memory immediately. Consider many corrections at once. Also, seems less picky if we don't.

Did you test it with CURL?

Keep Run script with nodemon or modify preference on own but don't remove it from package.json lol

**Comment by cheeseonamonkey** [comment]
Currently, the Server is using the Client's local file path.

So a CURL *only* works running *on the same machine - *any requests over
the web will not be able to access the file path of the Client.

**Comment by cheeseonamonkey** [comment]
We need the _contents_ of the file, or a buffer / binary stream of the file itself.

**Comment by hdbham** [comment]
Multer middleware is handling the buffer

https://expressjs.com/en/resources/middleware/multer.html

**Pull request closed without merging**
